### PR TITLE
Simplify calling by templating bitsize

### PR DESCRIPTION
**Pull request by filiatra**
This simplifies the calling interface. However, one can now only define a single encoding scheme for a specific bit-count. If this is OK, then this PR simplifes things..

### CODE REVIEW

**Comment by filiatra** [comment]
if many different encodings are needed, one could define a second template parameter in "encode" and "decode", e.g. an enum giving a name to the specific encoding..

**Comment by azawadzki** [comment]
First of all, thanks for a second PR! :)

I agree that bn::encode<32> looks tidier than bn::encode_b32, but it comes at the cost of changing the interface without adding other benefits than those pertaining to aesthetics (even the character count is the same). As you pointed out, it also takes away the possibility of adding multiple encodings for a single bit count, unless further changes to the interface are made (and these would likely make it actually a bit more complicated)

Though it looks nice, I'm leaning toward not changing the interface.

If I missed a benefit of the change in the comment above, could you kindly comment?

**Comment by filiatra** [comment]
Hi,
The benefits is exactly as you describe, no more or no less. It seemed fewer code lines to me, and easier to use with the templated bitsize. I think that further changes to accomodate diffrerent encodings are not too compilicated to do..

I fully understand that that you don't want to merge this, it is not really adding to functionality, I just felt the need to propose this idea that came to my mind! :)

**Comment by azawadzki** [comment]
Thanks for adding more context. I'll take the liberty of keeping the PR unmerged then.

**Pull request closed without merging**
